# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:\COMPUTER SCIENCE\virtual assistant\temp software\windchild.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_secondwindow(object):
    def setupUi(self, secondwindow):
        secondwindow.setObjectName("secondwindow")
        secondwindow.resize(480, 197)
        self.centralwidget = QtWidgets.QWidget(secondwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        secondwindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(secondwindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        secondwindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(secondwindow)
        self.statusbar.setObjectName("statusbar")
        secondwindow.setStatusBar(self.statusbar)

        self.retranslateUi(secondwindow)
        QtCore.QMetaObject.connectSlotsByName(secondwindow)

    def retranslateUi(self, secondwindow):
        _translate = QtCore.QCoreApplication.translate
        secondwindow.setWindowTitle(_translate("secondwindow", "MainWindow"))
        self.label.setText(_translate("secondwindow", "second window"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    secondwindow = QtWidgets.QMainWindow()
    ui = Ui_secondwindow()
    ui.setupUi(secondwindow)
    secondwindow.show()
    sys.exit(app.exec_())
