

from PyQt5 import QtCore, QtGui, QtWidgets

 
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(401, 641)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 401, 91))
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(2)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.outputLabel.setFont(font)
        self.outputLabel.setText("0")
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('%'))
        self.percentButton.setGeometry(QtCore.QRect(0, 100, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('C'))
        self.cButton.setGeometry(QtCore.QRect(100, 100, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.Buttonless = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('<<'))
        self.Buttonless.setGeometry(QtCore.QRect(200, 100, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Buttonless.setFont(font)
        self.Buttonless.setObjectName("Buttonless")
        self.divButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('/'))
        self.divButton.setGeometry(QtCore.QRect(300, 100, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.divButton.setFont(font)
        self.divButton.setObjectName("divButton")
        self.mulButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('*'))
        self.mulButton.setGeometry(QtCore.QRect(300, 200, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.mulButton.setFont(font)
        self.mulButton.setObjectName("mulButton")
        self.Button_8 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('8'))
        self.Button_8.setGeometry(QtCore.QRect(100, 200, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_8.setFont(font)
        self.Button_8.setObjectName("Button_8")
        self.Button_9 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('9'))
        self.Button_9.setGeometry(QtCore.QRect(200, 200, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_9.setFont(font)
        self.Button_9.setObjectName("Button_9")
        self.Button_7 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('7'))
        self.Button_7.setGeometry(QtCore.QRect(0, 200, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_7.setFont(font)
        self.Button_7.setObjectName("Button_7")
        self.subButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('-'))
        self.subButton.setGeometry(QtCore.QRect(300, 300, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.subButton.setFont(font)
        self.subButton.setObjectName("subButton")
        self.Button_5 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('5'))
        self.Button_5.setGeometry(QtCore.QRect(100, 300, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_5.setFont(font)
        self.Button_5.setObjectName("Button_5")
        self.Button_6 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('6'))
        self.Button_6.setGeometry(QtCore.QRect(200, 300, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_6.setFont(font)
        self.Button_6.setObjectName("Button_6")
        self.Button_4 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('4'))
        self.Button_4.setGeometry(QtCore.QRect(0, 300, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_4.setFont(font)
        self.Button_4.setObjectName("Button_4")
        self.Button_plus = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('+'))
        self.Button_plus.setGeometry(QtCore.QRect(300, 400, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_plus.setFont(font)
        self.Button_plus.setObjectName("Button_plus")
        self.Button_2 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('2'))
        self.Button_2.setGeometry(QtCore.QRect(100, 400, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_2.setFont(font)
        self.Button_2.setObjectName("Button_2")
        self.Button_3 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('3'))
        self.Button_3.setGeometry(QtCore.QRect(200, 400, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_3.setFont(font)
        self.Button_3.setObjectName("Button_3")
        self.Button_1 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('1'))
        self.Button_1.setGeometry(QtCore.QRect(0, 400, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_1.setFont(font)
        self.Button_1.setObjectName("Button_1")
        self.Button_0 = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('0'))
        self.Button_0.setGeometry(QtCore.QRect(100, 500, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Button_0.setFont(font)
        self.Button_0.setObjectName("Button_0")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(200, 500, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.pmButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it(''))
        self.pmButton.setGeometry(QtCore.QRect(0, 500, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pmButton.setFont(font)
        self.pmButton.setObjectName("pmButton")
        self.eqButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.press_it('='))
        self.eqButton.setGeometry(QtCore.QRect(300, 500, 101, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.eqButton.setFont(font)
        self.eqButton.setObjectName("eqButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 401, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def dot_it(self):
        screen = self.outputLabel.text()

        if "." in screen:
            pass
        else:
            self.outputLabel.setText(f'{screen}.')
    def press_it(self,pressed):
        if pressed == 'C':
            self.outputLabel.setText('0')
        else:
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.Buttonless.setText(_translate("MainWindow", "<<"))
        self.divButton.setText(_translate("MainWindow", "/"))
        self.mulButton.setText(_translate("MainWindow", "X"))
        self.Button_8.setText(_translate("MainWindow", "8"))
        self.Button_9.setText(_translate("MainWindow", "9"))
        self.Button_7.setText(_translate("MainWindow", "7"))
        self.subButton.setText(_translate("MainWindow", "-"))
        self.Button_5.setText(_translate("MainWindow", "5"))
        self.Button_6.setText(_translate("MainWindow", "6"))
        self.Button_4.setText(_translate("MainWindow", "4"))
        self.Button_plus.setText(_translate("MainWindow", "+"))
        self.Button_2.setText(_translate("MainWindow", "2"))
        self.Button_3.setText(_translate("MainWindow", "3"))
        self.Button_1.setText(_translate("MainWindow", "1"))
        self.Button_0.setText(_translate("MainWindow", "0"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.pmButton.setText(_translate("MainWindow", "+/-"))
        self.eqButton.setText(_translate("MainWindow", "="))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())